[package]
name = "duckarmor/gooey-particles"
description = "UI Particle System."
version = "0.1.0-beta"
license = "MIT"
authors = ["passhley", "benbrimeyer"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
