[package]
name = "passhley/gooey-particles"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.2"
Llama = "freddylist/llama@1.1.1"
